//
// Generated file, do not edit! Created by nedtool 4.6 from veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg.
//

#ifndef _AODVRELCONTROLPACKETS_M_H_
#define _AODVRELCONTROLPACKETS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "IPv4Address.h"
#include "simtime_t.h"
// }}

/**
 * Struct generated from veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg:29 by nedtool.
 */
struct UnreachableNode
{
    UnreachableNode();
    IPv4Address addr;
    unsigned int seqNum;
};

void doPacking(cCommBuffer *b, UnreachableNode& a);
void doUnpacking(cCommBuffer *b, UnreachableNode& a);

/**
 * Enum generated from <tt>veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg:35</tt> by nedtool.
 * <pre>
 * enum AODVRelControlPacketType
 * {
 * 
 *     RREQ = 1;
 *     RREP = 2;
 *     RERR = 3;
 *     RREPACK = 4;
 * }
 * </pre>
 */
enum AODVRelControlPacketType {
    RREQ = 1,
    RREP = 2,
    RERR = 3,
    RREPACK = 4
};

/**
 * Class generated from <tt>veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg:46</tt> by nedtool.
 * <pre>
 * //
 * // Base packet for AODVRel Control Packets
 * //
 * packet AODVRelControlPacket
 * {
 *     unsigned int packetType;
 * }
 * </pre>
 */
class AODVRelControlPacket : public ::cPacket
{
  protected:
    unsigned int packetType_var;

  private:
    void copy(const AODVRelControlPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AODVRelControlPacket&);

  public:
    AODVRelControlPacket(const char *name=NULL, int kind=0);
    AODVRelControlPacket(const AODVRelControlPacket& other);
    virtual ~AODVRelControlPacket();
    AODVRelControlPacket& operator=(const AODVRelControlPacket& other);
    virtual AODVRelControlPacket *dup() const {return new AODVRelControlPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
};

inline void doPacking(cCommBuffer *b, AODVRelControlPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AODVRelControlPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg:54</tt> by nedtool.
 * <pre>
 * //
 * // Represents an AODVRel Route Request
 * //
 * class AODVRelRREQ extends AODVRelControlPacket
 * {
 *     unsigned int packetType = RREQ;
 *     bool joinFlag;
 *     bool repairFlag;
 *     bool gratuitousRREPFlag;
 *     bool destOnlyFlag;
 *     bool unknownSeqNumFlag;
 *     unsigned int hopCount;
 *     unsigned int rreqId;
 *     IPv4Address destAddr;
 *     unsigned int destSeqNum;
 *     IPv4Address originatorAddr;
 *     unsigned int originatorSeqNum;
 * 
 *     // changes 1.1
 *     double XPosition;
 *     double YPosition;
 *     double XVelocity;
 *     double YVelocity;
 *     double routeReliability;
 * }
 * </pre>
 */
class AODVRelRREQ : public ::AODVRelControlPacket
{
  protected:
    unsigned int packetType_var;
    bool joinFlag_var;
    bool repairFlag_var;
    bool gratuitousRREPFlag_var;
    bool destOnlyFlag_var;
    bool unknownSeqNumFlag_var;
    unsigned int hopCount_var;
    unsigned int rreqId_var;
    IPv4Address destAddr_var;
    unsigned int destSeqNum_var;
    IPv4Address originatorAddr_var;
    unsigned int originatorSeqNum_var;
    double XPosition_var;
    double YPosition_var;
    double XVelocity_var;
    double YVelocity_var;
    double routeReliability_var;

  private:
    void copy(const AODVRelRREQ& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AODVRelRREQ&);

  public:
    AODVRelRREQ(const char *name=NULL);
    AODVRelRREQ(const AODVRelRREQ& other);
    virtual ~AODVRelRREQ();
    AODVRelRREQ& operator=(const AODVRelRREQ& other);
    virtual AODVRelRREQ *dup() const {return new AODVRelRREQ(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
    virtual bool getJoinFlag() const;
    virtual void setJoinFlag(bool joinFlag);
    virtual bool getRepairFlag() const;
    virtual void setRepairFlag(bool repairFlag);
    virtual bool getGratuitousRREPFlag() const;
    virtual void setGratuitousRREPFlag(bool gratuitousRREPFlag);
    virtual bool getDestOnlyFlag() const;
    virtual void setDestOnlyFlag(bool destOnlyFlag);
    virtual bool getUnknownSeqNumFlag() const;
    virtual void setUnknownSeqNumFlag(bool unknownSeqNumFlag);
    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);
    virtual unsigned int getRreqId() const;
    virtual void setRreqId(unsigned int rreqId);
    virtual IPv4Address& getDestAddr();
    virtual const IPv4Address& getDestAddr() const {return const_cast<AODVRelRREQ*>(this)->getDestAddr();}
    virtual void setDestAddr(const IPv4Address& destAddr);
    virtual unsigned int getDestSeqNum() const;
    virtual void setDestSeqNum(unsigned int destSeqNum);
    virtual IPv4Address& getOriginatorAddr();
    virtual const IPv4Address& getOriginatorAddr() const {return const_cast<AODVRelRREQ*>(this)->getOriginatorAddr();}
    virtual void setOriginatorAddr(const IPv4Address& originatorAddr);
    virtual unsigned int getOriginatorSeqNum() const;
    virtual void setOriginatorSeqNum(unsigned int originatorSeqNum);
    virtual double getXPosition() const;
    virtual void setXPosition(double XPosition);
    virtual double getYPosition() const;
    virtual void setYPosition(double YPosition);
    virtual double getXVelocity() const;
    virtual void setXVelocity(double XVelocity);
    virtual double getYVelocity() const;
    virtual void setYVelocity(double YVelocity);
    virtual double getRouteReliability() const;
    virtual void setRouteReliability(double routeReliability);
};

inline void doPacking(cCommBuffer *b, AODVRelRREQ& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AODVRelRREQ& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg:80</tt> by nedtool.
 * <pre>
 * //
 * // Represents an AODVRel Route Reply
 * //
 * class AODVRelRREP extends AODVRelControlPacket
 * {
 *     unsigned int packetType = RREP;
 *     bool repairFlag;
 *     bool ackRequiredFlag;
 *     unsigned int prefixSize;
 *     unsigned int hopCount;
 *     IPv4Address destAddr;
 *     unsigned int destSeqNum;
 *     IPv4Address originatorAddr;
 *     unsigned int originatorSeqNum;
 *     simtime_t lifeTime;
 * 
 *     // changes 1.1
 *     double XPosition;
 *     double YPosition;
 *     double XVelocity;
 *     double YVelocity;
 *     double routeReliability;
 *     double reverseRouteReliability;
 * }
 * </pre>
 */
class AODVRelRREP : public ::AODVRelControlPacket
{
  protected:
    unsigned int packetType_var;
    bool repairFlag_var;
    bool ackRequiredFlag_var;
    unsigned int prefixSize_var;
    unsigned int hopCount_var;
    IPv4Address destAddr_var;
    unsigned int destSeqNum_var;
    IPv4Address originatorAddr_var;
    unsigned int originatorSeqNum_var;
    simtime_t lifeTime_var;
    double XPosition_var;
    double YPosition_var;
    double XVelocity_var;
    double YVelocity_var;
    double routeReliability_var;
    double reverseRouteReliability_var;

  private:
    void copy(const AODVRelRREP& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AODVRelRREP&);

  public:
    AODVRelRREP(const char *name=NULL);
    AODVRelRREP(const AODVRelRREP& other);
    virtual ~AODVRelRREP();
    AODVRelRREP& operator=(const AODVRelRREP& other);
    virtual AODVRelRREP *dup() const {return new AODVRelRREP(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
    virtual bool getRepairFlag() const;
    virtual void setRepairFlag(bool repairFlag);
    virtual bool getAckRequiredFlag() const;
    virtual void setAckRequiredFlag(bool ackRequiredFlag);
    virtual unsigned int getPrefixSize() const;
    virtual void setPrefixSize(unsigned int prefixSize);
    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);
    virtual IPv4Address& getDestAddr();
    virtual const IPv4Address& getDestAddr() const {return const_cast<AODVRelRREP*>(this)->getDestAddr();}
    virtual void setDestAddr(const IPv4Address& destAddr);
    virtual unsigned int getDestSeqNum() const;
    virtual void setDestSeqNum(unsigned int destSeqNum);
    virtual IPv4Address& getOriginatorAddr();
    virtual const IPv4Address& getOriginatorAddr() const {return const_cast<AODVRelRREP*>(this)->getOriginatorAddr();}
    virtual void setOriginatorAddr(const IPv4Address& originatorAddr);
    virtual unsigned int getOriginatorSeqNum() const;
    virtual void setOriginatorSeqNum(unsigned int originatorSeqNum);
    virtual simtime_t getLifeTime() const;
    virtual void setLifeTime(simtime_t lifeTime);
    virtual double getXPosition() const;
    virtual void setXPosition(double XPosition);
    virtual double getYPosition() const;
    virtual void setYPosition(double YPosition);
    virtual double getXVelocity() const;
    virtual void setXVelocity(double XVelocity);
    virtual double getYVelocity() const;
    virtual void setYVelocity(double YVelocity);
    virtual double getRouteReliability() const;
    virtual void setRouteReliability(double routeReliability);
    virtual double getReverseRouteReliability() const;
    virtual void setReverseRouteReliability(double reverseRouteReliability);
};

inline void doPacking(cCommBuffer *b, AODVRelRREP& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AODVRelRREP& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg:105</tt> by nedtool.
 * <pre>
 * //
 * // Represents an AODVRel Route Error
 * //
 * class AODVRelRERR extends AODVRelControlPacket
 * {
 *     unsigned int packetType = RERR;
 *     UnreachableNode unreachableNodes[];
 *     bool noDeleteFlag;
 *     unsigned int destCount;
 * }
 * </pre>
 */
class AODVRelRERR : public ::AODVRelControlPacket
{
  protected:
    unsigned int packetType_var;
    UnreachableNode *unreachableNodes_var; // array ptr
    unsigned int unreachableNodes_arraysize;
    bool noDeleteFlag_var;
    unsigned int destCount_var;

  private:
    void copy(const AODVRelRERR& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AODVRelRERR&);

  public:
    AODVRelRERR(const char *name=NULL);
    AODVRelRERR(const AODVRelRERR& other);
    virtual ~AODVRelRERR();
    AODVRelRERR& operator=(const AODVRelRERR& other);
    virtual AODVRelRERR *dup() const {return new AODVRelRERR(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
    virtual void setUnreachableNodesArraySize(unsigned int size);
    virtual unsigned int getUnreachableNodesArraySize() const;
    virtual UnreachableNode& getUnreachableNodes(unsigned int k);
    virtual const UnreachableNode& getUnreachableNodes(unsigned int k) const {return const_cast<AODVRelRERR*>(this)->getUnreachableNodes(k);}
    virtual void setUnreachableNodes(unsigned int k, const UnreachableNode& unreachableNodes);
    virtual bool getNoDeleteFlag() const;
    virtual void setNoDeleteFlag(bool noDeleteFlag);
    virtual unsigned int getDestCount() const;
    virtual void setDestCount(unsigned int destCount);
};

inline void doPacking(cCommBuffer *b, AODVRelRERR& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AODVRelRERR& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg:116</tt> by nedtool.
 * <pre>
 * //
 * // Represents an AODVRel Route Reply ACK
 * //
 * class AODVRelRREPACK extends AODVRelControlPacket
 * {
 *     unsigned int packetType = RREPACK;
 * }
 * </pre>
 */
class AODVRelRREPACK : public ::AODVRelControlPacket
{
  protected:
    unsigned int packetType_var;

  private:
    void copy(const AODVRelRREPACK& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AODVRelRREPACK&);

  public:
    AODVRelRREPACK(const char *name=NULL);
    AODVRelRREPACK(const AODVRelRREPACK& other);
    virtual ~AODVRelRREPACK();
    AODVRelRREPACK& operator=(const AODVRelRREPACK& other);
    virtual AODVRelRREPACK *dup() const {return new AODVRelRREPACK(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
};

inline void doPacking(cCommBuffer *b, AODVRelRREPACK& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AODVRelRREPACK& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>veins/networklayer/routing/AODVRel/AODVRelControlPackets.msg:124</tt> by nedtool.
 * <pre>
 * //
 * // Represents a timer for a Route Reply packet
 * //
 * message WaitForRREP
 * {
 *     IPv4Address destAddr;
 *     unsigned int lastTTL;
 *     bool fromInvalidEntry;
 * }
 * </pre>
 */
class WaitForRREP : public ::cMessage
{
  protected:
    IPv4Address destAddr_var;
    unsigned int lastTTL_var;
    bool fromInvalidEntry_var;

  private:
    void copy(const WaitForRREP& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WaitForRREP&);

  public:
    WaitForRREP(const char *name=NULL, int kind=0);
    WaitForRREP(const WaitForRREP& other);
    virtual ~WaitForRREP();
    WaitForRREP& operator=(const WaitForRREP& other);
    virtual WaitForRREP *dup() const {return new WaitForRREP(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual IPv4Address& getDestAddr();
    virtual const IPv4Address& getDestAddr() const {return const_cast<WaitForRREP*>(this)->getDestAddr();}
    virtual void setDestAddr(const IPv4Address& destAddr);
    virtual unsigned int getLastTTL() const;
    virtual void setLastTTL(unsigned int lastTTL);
    virtual bool getFromInvalidEntry() const;
    virtual void setFromInvalidEntry(bool fromInvalidEntry);
};

inline void doPacking(cCommBuffer *b, WaitForRREP& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, WaitForRREP& obj) {obj.parsimUnpack(b);}


#endif // ifndef _AODVRELCONTROLPACKETS_M_H_

